name: ilkersevim_json_isolate_example
publish_to: none

environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: '>=3.47.0'

dependencies:
  flutter:
    sdk: flutter
  ilkersevim_json_isolate:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
